"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { browserSupabase } from "@/lib/supabase/browser";
import { maxPadSizeBytes } from "@/lib/validation/pad";
type Pad = { content: string; updated_at: string; expires_at: string };
type Status = "Loading…" | "Saved" | "Saving…" | "Offline" | "Reconnecting…" | "Unsaved changes";
export default function PadEditor({ sessionId }: { sessionId: string }) {
 const [content, setContent] = useState(""); const [status, setStatus] = useState<Status>("Loading…"); const [error, setError] = useState(""); const [ready, setReady] = useState(false);
 const contentRef = useRef(""); const dirty = useRef(false); const timer = useRef<ReturnType<typeof setTimeout> | null>(null); const latestAt = useRef("");
 const load = useCallback(async () => { try { const response = await fetch(`/api/pads/${sessionId}`, { cache: "no-store" }); const data = await response.json(); if (!response.ok) { setError(data.error ?? "Unable to load this pad."); return; } const pad = data as Pad; if (!dirty.current) { contentRef.current = pad.content; setContent(pad.content); latestAt.current = pad.updated_at; } setStatus(dirty.current ? "Unsaved changes" : "Saved"); setReady(true); } catch { setStatus("Offline"); setError("Unable to reach BridgePad. Your local edits will stay here until you retry."); } }, [sessionId]);
 const save = useCallback(async () => { timer.current = null; if (!dirty.current) return; setStatus("Saving…"); try { const response = await fetch(`/api/pads/${sessionId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ content: contentRef.current }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); latestAt.current = data.updated_at; dirty.current = false; setError(""); setStatus("Saved"); } catch (reason) { setStatus("Unsaved changes"); setError(reason instanceof Error ? reason.message : "Unable to save. Your text remains in this browser."); } }, [sessionId]);
 const queueSave = useCallback(() => { if (timer.current) clearTimeout(timer.current); timer.current = setTimeout(save, 400); }, [save]);
 useEffect(() => { void load(); const client = browserSupabase(); const channel = client.channel(`pad:${sessionId}`).on("postgres_changes", { event: "UPDATE", schema: "public", table: "pads", filter: `session_id=eq.${sessionId}` }, payload => { const next = payload.new as Pad; if (new Date(next.expires_at) <= new Date()) return; if (next.updated_at <= latestAt.current || next.content === contentRef.current) { latestAt.current = next.updated_at; return; } latestAt.current = next.updated_at; if (dirty.current) { setStatus("Unsaved changes"); setError("A newer shared change arrived while you were editing. Your local change will be saved next (last write wins)."); return; } contentRef.current = next.content; setContent(next.content); setStatus("Saved"); }).subscribe(state => { if (state === "SUBSCRIBED") { void load(); } else if (state === "CHANNEL_ERROR" || state === "TIMED_OUT") setStatus("Reconnecting…"); else if (state === "CLOSED") setStatus("Offline"); });
 return () => { if (timer.current) clearTimeout(timer.current); void client.removeChannel(channel); }; }, [load, sessionId]);
 function onChange(value: string) { if (new TextEncoder().encode(value).byteLength > maxPadSizeBytes()) { setError(`Pad content is limited to ${maxPadSizeBytes()} bytes.`); return; } contentRef.current = value; dirty.current = true; setContent(value); setStatus("Saving…"); setError(""); queueSave(); }
 function clear() { if (!window.confirm("Clear this pad? This will remove the contents for everyone currently using it.")) return; onChange(""); }
 if (error && !ready) return <section className="py-10"><p role="alert" className="text-red-700">{error}</p><Link className="mt-4 inline-block underline" href="/">Create a new pad.</Link></section>;
 return <section className="flex min-h-0 flex-1 flex-col"><label htmlFor="pad-content" className="sr-only">Shared note content</label><textarea id="pad-content" value={content} onChange={event => onChange(event.target.value)} placeholder="Start typing or paste text here..." disabled={!ready} className="mt-5 min-h-72 flex-1 resize-y rounded-md border border-slate-300 bg-white p-4 leading-6 shadow-sm disabled:bg-slate-100" /><div className="mt-3 flex flex-wrap items-center justify-between gap-3 text-sm"><p aria-live="polite" className="text-slate-600">{status}</p><button onClick={clear} disabled={!ready} className="rounded-md border border-slate-300 px-3 py-2 hover:bg-slate-100 disabled:opacity-60">Clear Pad</button></div>{error && <p role="alert" className="mt-2 text-sm text-amber-800">{error}</p>}</section>;
}
